-- ========================================================
-- AL PARFUME - SUPABASE DATABASE MIGRATION SCRIPT (TAHAP 1 REVISI FINAL UUID FIX)
-- ========================================================

-- 1. TABEL CATEGORIES (Publik bisa membaca katalog kategori)
CREATE TABLE IF NOT EXISTS categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read categories" ON categories;
CREATE POLICY "Public read categories" ON categories FOR SELECT USING (true);

-- 2. ALTER TABEL EXISTING (products & product_variants)
-- Hasil inspeksi live DB: products.id = UUID, product_variants.id = UUID
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS category_id UUID REFERENCES categories(id) ON DELETE SET NULL;

ALTER TABLE product_variants 
ADD COLUMN IF NOT EXISTS stock INT NOT NULL DEFAULT 100;

-- Kebijakan RLS Idempotent untuk products & product_variants
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Public read products') THEN
        CREATE POLICY "Public read products" ON products FOR SELECT USING (true);
    END IF;
END $$;

ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'product_variants' AND policyname = 'Public read product_variants') THEN
        CREATE POLICY "Public read product_variants" ON product_variants FOR SELECT USING (true);
    END IF;
END $$;


-- ========================================================
-- TABEL TRANSAKSI & PRIVASI (RLS FULLY LOCKED DOWN FOR ANON)
-- Seluruh akses write & read dilakukan via Next.js API Routes (Server-Side Service Role Key)
-- ========================================================

-- 3. TABEL CUSTOMERS (Data Privasi Pelanggan)
CREATE TABLE IF NOT EXISTS customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    wa_number VARCHAR(50) NOT NULL,
    address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_customers_wa_number ON customers(wa_number);
CREATE INDEX IF NOT EXISTS idx_customers_name_wa ON customers(name, wa_number);

-- LOCKDOWN RLS: Tidak ada policy publik. Akses HANYA via Service Role Key di server API.
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;


-- 4. TABEL ORDERS
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code VARCHAR(100) NOT NULL UNIQUE,
    customer_id UUID REFERENCES customers(id) ON DELETE RESTRICT,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    shipping_cost NUMERIC(12, 2) NOT NULL DEFAULT 0,
    delivery_method VARCHAR(50) NOT NULL DEFAULT 'courier', -- 'courier' / 'pickup'
    grand_total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payment_method VARCHAR(50) NOT NULL DEFAULT 'qris',    -- 'qris' / 'cod_pickup'
    payment_status VARCHAR(50) NOT NULL DEFAULT 'pending_verification', -- 'pending_verification', 'paid', 'cancelled'
    fulfillment_status VARCHAR(50) NOT NULL DEFAULT 'pending', -- 'pending', 'processing', 'shipped', 'ready_for_pickup', 'completed'
    tracking_number VARCHAR(100),
    order_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_order_code ON orders(order_code);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);

-- LOCKDOWN RLS: Tidak ada policy publik. Akses HANYA via Service Role Key di server API.
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;


-- 5. TABEL ORDER_ITEMS (variant_id disesuaikan tipe UUID sesuai live database)
CREATE TABLE IF NOT EXISTS order_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    variant_id UUID REFERENCES product_variants(id) ON DELETE SET NULL,
    product_name_snapshot VARCHAR(255) NOT NULL,
    size_ml_snapshot INT NOT NULL,
    qty INT NOT NULL DEFAULT 1,
    price_snapshot NUMERIC(12, 2) NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_variant_id ON order_items(variant_id);

-- LOCKDOWN RLS: Tidak ada policy publik. Akses HANYA via Service Role Key di server API.
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;


-- 6. TABEL PAYMENT_PROOFS (Satu-satunya sumber data foto bukti bayar)
CREATE TABLE IF NOT EXISTS payment_proofs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    verified_by VARCHAR(255),
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payment_proofs_order_id ON payment_proofs(order_id);

-- LOCKDOWN RLS: Tidak ada policy publik. Akses HANYA via Service Role Key di server API.
ALTER TABLE payment_proofs ENABLE ROW LEVEL SECURITY;


-- 7. TABEL ORDER_STATUS_LOG (Audit Trail Status Order)
CREATE TABLE IF NOT EXISTS order_status_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    status_type VARCHAR(50) NOT NULL, -- 'payment' / 'fulfillment'
    status_value VARCHAR(50) NOT NULL,
    changed_by VARCHAR(255) NOT NULL DEFAULT 'system', -- Diisi Email Admin dari session
    changed_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_order_status_log_order_id ON order_status_log(order_id);

-- LOCKDOWN RLS: Akses HANYA via Service Role Key di server API.
ALTER TABLE order_status_log ENABLE ROW LEVEL SECURITY;


-- 8. TABEL STOCK_MOVEMENTS (variant_id disesuaikan tipe UUID sesuai live database)
CREATE TABLE IF NOT EXISTS stock_movements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    variant_id UUID NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
    change_qty INT NOT NULL,
    reason VARCHAR(50) NOT NULL, -- 'order', 'restock', 'correction', 'cancellation', 'refund'
    reference_order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_stock_movements_variant_id ON stock_movements(variant_id);

-- LOCKDOWN RLS: Akses HANYA via Service Role Key di server API.
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;


-- ========================================================
-- POSTGRES FUNCTIONS (ATOMIC STOCK OPERATIONS - UUID VARIANT ID)
-- ========================================================

CREATE OR REPLACE FUNCTION deduct_product_stock(
    p_variant_id UUID,
    p_qty INT,
    p_order_id BIGINT
) RETURNS BOOLEAN AS $$
DECLARE
    v_updated_rows INT;
BEGIN
    UPDATE product_variants
    SET stock = stock - p_qty
    WHERE id = p_variant_id AND stock >= p_qty;
    
    GET DIAGNOSTICS v_updated_rows = ROW_COUNT;
    
    IF v_updated_rows > 0 THEN
        INSERT INTO stock_movements (variant_id, change_qty, reason, reference_order_id)
        VALUES (p_variant_id, -p_qty, 'order', p_order_id);
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION restore_product_stock(
    p_variant_id UUID,
    p_qty INT,
    p_order_id BIGINT,
    p_reason VARCHAR
) RETURNS VOID AS $$
BEGIN
    UPDATE product_variants
    SET stock = stock + p_qty
    WHERE id = p_variant_id;
    
    INSERT INTO stock_movements (variant_id, change_qty, reason, reference_order_id)
    VALUES (p_variant_id, p_qty, COALESCE(p_reason, 'cancellation'), p_order_id);
END;
$$ LANGUAGE plpgsql;
